# 版本号
version: "3"
services:
  mysql:
    # mysql容器的名称
    container_name: tiktok-mysql
    environment:
      TZ: Asia/Shanghai #timeZone 时区
      # 指定MySQL root用户的密码
      MYSQL_ROOT_PASSWORD: 'your MySQL root password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      # 这里这个指令compose启动成功后会自动创建名为simple_tiktok的数据库
      MYSQL_DATABASE: 'simple_tiktok'
      # 此处就是相当于 mysql create user，创建了数据库的登录用户
      MYSQL_USER: 'tiktok'
      MYSQL_PASSWORD: 'tiktokabc'
    image: mysql:latest
    # 使用主机的33306端口映射docker MySQL容器的3306端口
    ports:
      - "33306:3306"
    volumes:
      # 同步宿主机的时区
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - ./config/docker/mysql/data:/var/lib/mysql
      # 这里的my.cnf可以从原来的安装的MySQL里面找，如果没有不配置也不影响，只是为了方便外部更改
      - ./config/docker/mysql/conf/my.cnf:/etc/my.cnf
      - ./config/docker/mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password